AppBundle\Entity\ConfigKey:
    type: entity
    repositoryClass: AppBundle\Entity\ConfigKeyRepository
    table: config_key
    indexes:
        file_path_index:
            columns: [ file, path ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        file:
            type: string
            length: 100
        path:
            type: string
            length: 255
    oneToMany:
        values:
            targetEntity: ConfigValue
            mappedBy: configKey